options:
  formatter: stylish
  convention-explanation: 'SASS Standard - Protime adjustment'
files:
  include:
    - 'src/**/*.s+(a|c)ss'
  ignore:
    - 'src/stylesheets/vendors/**/*.s+(a|c)ss'
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 1

  # Line Spacing
  one-declaration-per-line: 1
  empty-line-between-blocks: 1
  single-line-per-selector: 1

  # Disallows
  declarations-before-nesting: 1
  no-color-keywords: 1
  no-color-literals: 1
  no-css-comments: 0
  no-debug: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-extends: 0
  no-ids: 1
  no-important: 0                 # Should be an error, but requires some changes on legacy files
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements:
    - 1
    -
      allow-element-with-attribute: true
      allow-element-with-class: true
      allow-element-with-id: false

  no-trailing-zero: 1
  no-transition-all: 0            # Should be an error, performance impact and unpredictable
  no-url-protocols: 0
  no-url-domains: 0
  no-vendor-prefixes: 1
  no-warn: 1
  property-units: 0

  # Nesting
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format:
    - 0                         # NO warning, this is unusable because of the amount of warnings, we want to set this as an error once all components have been converted to CSS modules
    -
      convention: 'camelcase'

  function-name-format: 1
  id-name-format: 0
  mixin-name-format: 1
  placeholder-name-format:
    - 1
    -
      convention: 'camelcase'

  variable-name-format: 0
  clean-import-paths: 0

  # Style Guide
  bem-depth: 0
  border-zero:
    - 1
    -
      convention: 'none'

  brace-style:
    - 1
    -
      style: '1tbs'
      allow-single-line: true

  empty-args: 1
  hex-length:
    - 1
    -
      style: 'long'
  hex-notation:
    - 1
    -
      style: 'uppercase'
  indentation:
    - 1
    -
      size: 2

  leading-zero: 0
  nesting-depth:
    - 1
    -
      max-depth: 5

  property-sort-order:
    - 1
    -
      order: 'smacss'

  quotes: 1
  shorthand-values: 1
  url-quotes: 1
  variable-for-property: 1
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 1
  space-before-colon: 1
  space-after-colon: 1
  space-before-brace: 1
  space-before-bang: 1
  space-after-bang: 1
  space-between-parens: 1
  space-around-operator: 1

  # Final Items
  trailing-semicolon: 1
  final-newline: 1